#!/usr/bin/expect
set timeout 3
spawn vue init . vue-testbed
expect "downloading template"
send "\r"
expect "Application Name"
send "vue-testbed\r"
expect "Application Id (no dash)"
send "fr.soixantecircuits.vuetestbed\r"
expect "Application Version"
send "\r"
expect "Project description"
send "A vue test app\r"
expect "Use Sass / Scss?"
send "\r"
expect "Select which Vue plugins to install (vuex-electron not supported with vue-spacebro-client)"
send "\r"
expect "Use linting with ESLint?"
send "\r"
expect "Which ESLint config would you like to use?"
send "\r"
expect "Set up unit testing with Karma + Mocha?"
send "\r"
expect "Set up end-to-end testing with Spectron + Mocha?"
send "\r"
expect "What build tool would you like to use? Should be Electron packager for Interactive App"
send "\r"
expect "Setup service-worker?"
send "\r"
expect "author"
send "robot\r"
expect "Generated"
send "\r"
interact